CREATE TABLE commerces (
    id INTEGER PRIMARY KEY,
    idLocalisation INTEGER,
    categorie VARCHAR(128),
    idAttributs INTEGER NOT NULL,
    stars INTEGER NOT NULL,
    CONSTRAINT fk_commerces_attributs FOREIGN KEY (idAttributs) REFERENCES attributsCommerces(id),
    CONSTRAINT fk_commerces_localisation FOREIGN KEY (idLocalisation) REFERENCES localisation(id)
);

CREATE TABLE attributsCommerces (
    id INTEGER PRIMARY KEY,
    AcceptsInsurance BOOLEAN NOT NULL,
    AgesAllowed BOOLEAN NOT NULL,
    Alcohol BOOLEAN NOT NULL,
    Ambience BOOLEAN NOT NULL,
    BYOB BOOLEAN NOT NULL,
    BYOBCorkage BOOLEAN NOT NULL,
    BestNights BOOLEAN NOT NULL,
    BikeParking BOOLEAN NOT NULL,
    BusinessAcceptsBitcoin BOOLEAN NOT NULL,
    BusinessAcceptsCreditCards BOOLEAN NOT NULL,
    BusinessParking BOOLEAN NOT NULL,
    ByAppointmentOnly BOOLEAN NOT NULL,
    Caters BOOLEAN NOT NULL,
    CoatCheck BOOLEAN NOT NULL,
    Corkage BOOLEAN NOT NULL,
    DietaryRestrictions BOOLEAN NOT NULL,
    DogsAllowed BOOLEAN NOT NULL,
    DriveThru BOOLEAN NOT NULL,
    GoodForDancing BOOLEAN NOT NULL,
    GoodForKids BOOLEAN NOT NULL,
    GoodForMeal BOOLEAN NOT NULL,
    HairSpecializesIn BOOLEAN NOT NULL,
    HappyHour BOOLEAN NOT NULL,
    HasTV BOOLEAN NOT NULL,
    Music BOOLEAN NOT NULL,
    NoiseLevel BOOLEAN NOT NULL,
    Open24Hours BOOLEAN NOT NULL,
    OutdoorSeating BOOLEAN NOT NULL,
    RestaurantsAttire BOOLEAN NOT NULL,
    RestaurantsCounterService BOOLEAN NOT NULL,
    RestaurantsDelivery BOOLEAN NOT NULL,
    RestaurantsGoodForGroups BOOLEAN NOT NULL,
    RestaurantsPriceRange2 BOOLEAN NOT NULL,
    RestaurantsReservations BOOLEAN NOT NULL,
    RestaurantsTableService BOOLEAN NOT NULL,
    RestaurantsTakeOut BOOLEAN NOT NULL,
    Smoking BOOLEAN NOT NULL,
    WheelchairAccessible BOOLEAN NOT NULL,
    WiFi BOOLEAN NOT NULL
);